repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check # linter
        args: [--fix, --exit-non-zero-on-fix] # sort imports and fix
      - id: ruff-format # formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        entry: prettier --experimental-cli --write --ignore-unknown --no-cache
        additional_dependencies:
          - prettier@3.8.1
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer

  - repo: https://github.com/seqeralabs/nf-lint-pre-commit
    rev: v0.2.0
    hooks:
      - id: nextflow-lint
        files: '\.nf$|nextflow\.config$'

  - repo: local
    hooks:
      - id: codeowners-validator
        name: CODEOWNERS validator
        language: docker_image
        pass_filenames: false
        entry: >
          -e REPOSITORY_PATH="."
          -e CHECKS="files,duppatterns,syntax"
          ghcr.io/mszostok/codeowners-validator:v0.7.4
